name: Update Dependencies

on:
  schedule:
    - cron: '0 8 * * 1' # Runs every Monday at 10 AM EET (8 AM UTC)
  workflow_dispatch: # Allows for manual triggering

jobs:
  update-dependencies:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install Dependencies
        run: yarn install

      - name: Use Dependency Update Action
        uses: ./
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
