name: Update Dependencies

on:
  workflow_dispatch:

jobs:
  update-dependencies:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install Dependencies
        run: yarn install

      - name: Use Dependency Update Action
        uses: ./
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
        env:
          BASE_BRANCH: master
